defaults:
  - renderer_kwargs: smplx  # smplx / flame / smal
  - sliders_limiters: smplx  # smplx / smpl / flame / smal

# where to save the output
out_dir:  # fill

image_path:  # if you want to fit the model to an image, set the image path here
image2shape: False  # if True, then the image_path should be set, and the model will be fitted to the image
A_pose: False  # should the model be in A pose, if False, then T pose
show_values: False  # whether to show the values of the sliders or hide them

### CHOOSE ONE OF THE FOLLOWING:
# Body Shape
model_type: smplx  # smplx / smpl
gender: male  # male / female / neutral
# model_path: ${get_model_abs_path:${model_type}, ${gender}}
model_path: /home/nadav2/dev/data/CLIP2Shape/outs/images_to_shape/celebrities/data/smplx_male_5k.ckpt

# # Face Shape / Expression 
# model_type: flame
# specific: expression  # expression / shape
# model_path: ${get_model_abs_path:${model_type}, ${specific}}

# # Animal Shape
# model_type: smal
# specific:
# model_path: ${get_model_abs_path:${model_type}, ${specific}}

# GENERIC
# with_face: false
# on_parameters: True
# num_coeffs: 10

renderer_kwargs:
  img_size: [1024, 1024]
  use_tex: True
  model_type: ${model_type}
  py3d: True