name: semantify
channels:
  - conda-forge
  - pytorch
  - pytorch3d
  - anaconda
  - nvidia
dependencies:
  - python=3.8.13
  - pytorch=1.9.1=py3.8_cuda11.1_cudnn8.0.5_0
  - torchvision=0.10.1
  - cudatoolkit=11.1.74
  - pytorch3d=0.6.1=py38_cu111_pyt191
  - pip=20.3.1
  - pip:      
      - imutils==0.5.4
      - scipy==1.9.0
      - open3d==0.14.1
      - opencv-python==4.5.5.62
      - dataclass-dict-convert==1.7.0
      - networkx==2.8.6
      - scikit-image==0.19.3
      - tensorboard==2.11.2
      - omegaconf==2.1.2
      - attrdict==2.0.1
      - nltk==3.7
      - pytorch_lightning==1.5.7
      - chumpy==0.70
      - trimesh==3.16.0
      - imageio==2.21.3
      - hydra-core==1.1.1
      - Pillow==9.2.0
      - tqdm==4.64.0
      - smplx==0.1.28
      - altair==4.2.0
      - git+https://github.com/openai/CLIP.git
