DEFAULT_RENDERER_KWARGS = {
    "py3d": True,
    "img_size": [1024, 1024],
    "use_tex": False,
    "texture_optimization": False,
    "background_color": [0.0, 0.0, 0.0],
}


DESCRIPTORS = {
    "FLAME_SHAPE": [
        "fat",
        "thin",
        "long neck",
        "big forehead",
        "nose sticking-out",
        "ears sticking-out",
        "small chin",
        "long head",
        "chubby cheeks",
        "big head",
    ],
    "FLAME_EXPRESSION": [
        "happy",
        "sad",
        "angry",
        "surprised",
        "disgusted",
        "fearful",
        "neutral",
        "smiling",
        "serious",
        "pensive",
        "confused",
        "bored",
        "sleepy",
        "tired",
        "excited",
        "relaxed",
        "calm",
        "nervous",
        "worried",
        "scared",
        "open mouth",
        "raise eyebrows",
        "open eyes",
        "smile",
    ],
    "SMAL": ["hippo", "donkey", "horse", "cow", "lion", "cat", "dog"],
    "SMPLX_FEMALE": [
        "fat",
        "thin",
        "hourglass",
        "short",
        "long legs",
        "narrow waist",
        "skinny",
        "tall",
        "broad shoulders",
        "pear shaped",
        "average",
        "big",
        "curvy",
        "lean",
        "proportioned",
        "sexy",
        "fit",
        "heavyset",
        "petite",
        "small",
    ],
    "SMPLX_MALE": [
        "short",
        "tall",
        "long legs",
        "big",
        "fat",
        "broad shoulders",
        "built",
        "curvy",
        "fit",
        "heavyset",
        "lean",
        "long torso",
        "long",
        "muscular",
        "pear shaped",
        "petite",
        "proportioned",
        "rectangular",
        "round apple",
        "short legs",
        "short torso",
        "skinny",
        "small",
        "stocky",
        "sturdy",
        "narrow waist",
        "thin",
    ],
    "SMPLX_NEUTRAL": [
        "short",
        "tall",
        "long legs",
        "big",
        "fat",
        "curvy",
        "feminine",
        "fit",
        "heavyset",
        "lean",
        "long torso",
        "long",
        "masculine",
        "muscular",
        "pear shaped",
        "petite",
        "proportioned",
        "rectangular",
        "round apple",
        "short legs",
        "short torso",
        "skinny",
        "small",
        "stocky",
        "sturdy",
        "attractive",
        "sexy",
        "narrow waist",
        "hourglass",
    ],
}
